spring.application.name=MEDIA-SERVICE

server.port=8083

spring.mongodb.uri=mongodb://localhost:27019/mediadb

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true


minio.url=http://localhost:9000
minio.access.name=amazighi
minio.access.secret=secretamazighi
minio.bucket.name=buy01-media


spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

