# Server
server.port=8081

# Application
spring.application.name=user-service

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/buy01

# JWT
jwt.secret=your-256-bit-secret-key-here-change-in-prod
jwt.expiration=86400000

# Actuator
management.endpoints.web.exposure.include=health