# Server
server.port=8082

# Application
spring.application.name=PRODUCT-SERVICE

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27018/productdb

# JWT
jwt.secret=your-256-bit-secret-key-here-change-in-prod
jwt.expiration=86400000

# Actuator 
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Eureka Client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# kafka
spring.kafka.bootstrap-servers=kafka:9092
# spring.kafka.bootstrap-servers=localhost:9092
# spring.kafka.consumer.group-id=product-service-group
# spring.kafka.consumer.group-id=debug-group
spring.kafka.consumer.auto-offset-reset=earliest
# spring.kafka.bootstrap-servers: localhost:9092
# spring.kafka.consumer.properties.reconnect.backoff.ms: 5000
# spring.kafka.consumer.properties.reconnect.backoff.max.ms: 30000
spring.kafka.producer.retries: 3
