spring.application.name=${SPRING_APPLICATION_NAME:eureka-server}
server.port=${SERVER_PORT:8761}

eureka.instance.hostname=eureka-server
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka}

eureka.server.enable-self-preservation=false
eureka.instance.prefer-ip-address=true
